data:
  train_path: "data/train"
  test_path: "data/test"
  val_split: 0.2
  input_size: [224, 224]

preprocessing:
  clahe_clip_limit: 2.0
  clahe_grid_size: [8, 8]
  denoise_h: 10
  edge_sigma: 2.0

augmentation:
  rotation_range: 20
  shift_range: 0.1
  zoom_range: 0.1
  noise_sigma: 0.03

model:
  dense_layers: [1024, 512, 256]
  dropout_rates: [0.5, 0.4, 0.3]
  learning_rate: 0.001
  batch_size: 32
  epochs: 100